services:
  web:
    image: web:$TAG
    command: mix phx.server
    ports:
        - 4000
    env_file: .env
    depends_on:
        - db
  db:
    image: postgres:13.2-alpine
    expose:
        - 5432
    environment:
        - POSTGRES_USER=$DB_USER
        - POSTGRES_PASSWORD=$DB_PASSWORD
        - POSTGRES_DB=$DB_NAME